return {
	{ 'nvim-lualine/lualine.nvim', opts = {} },
	{ 'akinsho/toggleterm.nvim', opts = {} },
	{ 'ellisonleao/gruvbox.nvim' },
	{ 'stevearc/oil.nvim', opts = {} },
	{ 'folke/trouble.nvim', opts = {} },
	'folke/persistence.nvim',
	{ 'folke/persistence.nvim', event = 'BufReadPre', opts = {} },
	'nvim-telescope/telescope.nvim',
	{ 'romgrk/barbar.nvim', dependencies = { 'nvim-tree/nvim-web-devicons' } },
	-- { 'folke/noice.nvim', event = 'VeryLazy', opts = {}, dependencies = { 'MunifTanjim/nui.nvim', { 'rcarriga/nvim-notify', opts = {background_colour = '#000000'} } }, },
	'goolord/alpha-nvim',
	'neovim/nvim-lspconfig',
	'hrsh7th/cmp-nvim-lsp',
	'hrsh7th/cmp-buffer',
	'hrsh7th/cmp-path',
	'hrsh7th/cmp-cmdline',
	'hrsh7th/nvim-cmp',
	'hrsh7th/cmp-vsnip',
	'hrsh7th/vim-vsnip',
	'mattn/emmet-vim',
	'dcampos/cmp-emmet-vim',
	{ 'lukas-reineke/indent-blankline.nvim', main = 'ibl', opts = {} },
	-- { 'Exafunction/codeium.nvim', dependencies = { 'nvim-lua/plenary.nvim' }, opts = { enable_chat = true } },
	'nvim-treesitter/nvim-treesitter',
	'fatih/vim-go',
	{ 'folke/flash.nvim', event = 'VeryLazy', opts = { modes = { search = { enabled = true } } } },
	{ 'windwp/nvim-autopairs', event = 'InsertEnter', config = true },
	{ '2kabhishek/nerdy.nvim', dependencies = { 'stevearc/dressing.nvim', 'nvim-telescope/telescope.nvim' }, cmd = 'Nerdy' },
	{
		'christoomey/vim-tmux-navigator',
		cmd = {
			'TmuxNavigateLeft',
			'TmuxNavigateDown',
			'TmuxNavigateUp',
			'TmuxNavigateRight',
			'TmuxNavigatePrevious',
		},
		keys = {
			{ '<c-h>', '<cmd><C-U>TmuxNavigateLeft<cr>' },
			{ '<c-j>', '<cmd><C-U>TmuxNavigateDown<cr>' },
			{ '<c-k>', '<cmd><C-U>TmuxNavigateUp<cr>' },
			{ '<c-l>', '<cmd><C-U>TmuxNavigateRight<cr>' },
			{ '<c-\\>', '<cmd><C-U>TmuxNavigatePrevious<cr>' },
		},
	},
	{ 'numToStr/Comment.nvim', opts = {} },
	{ 'kylechui/nvim-surround', event = 'VeryLazy', opts = {} },
}
